/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClothingShop;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author tmurd
 */
public class StockManagement extends javax.swing.JFrame {

    /**
     * Creates new form StockManagement
     */
    
    private static final String dbURL = "jdbc:ucanaccess://FE2Project.accdb";
    private static java.sql.Connection con;
    private static java.sql.PreparedStatement ps;
    private DefaultTableModel model = new DefaultTableModel(new String[]{"ItemID", "Brand", "Type", "Colour", "Size","Price","Quantity"}, 0);
    
    public StockManagement() {
        initComponents();
        getTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        supplierTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        brandTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        typeCB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        colourTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sizeCB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        priceTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        quantityTF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        removeBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        stockTBL = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        editBTN = new javax.swing.JButton();
        refreshBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SupplyID");

        supplierTF.setText("supplierTF");

        jLabel2.setText("Brand");

        brandTF.setText("brandTF");

        jLabel3.setText("Type");

        typeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T-Shirt", "Jeans", "Trousers", "Sweatshirt", "Hoodie", "Tracksuit", "Jacket", "Shirts", "Suits", "Shorts" }));

        jLabel4.setText("Colour");

        colourTF.setText("colourTF");

        jLabel5.setText("Size");

        sizeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large", "X-Large" }));

        jLabel6.setText("Price");

        priceTF.setText("jTextField4");

        jLabel7.setText("Quantity");

        quantityTF.setText("quantityTF");

        addBTN.setText("ADD");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        removeBTN.setText("REMOVE");
        removeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBTNActionPerformed(evt);
            }
        });

        clearBTN.setText("CLEAR");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        stockTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(stockTBL);

        jLabel8.setText("Inventory List");

        editBTN.setText("EDIT");
        editBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTNActionPerformed(evt);
            }
        });

        refreshBTN.setText("Refresh");
        refreshBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBTNActionPerformed(evt);
            }
        });

        backBTN.setText("BACK");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(editBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(supplierTF)
                            .addComponent(typeCB, 0, 122, Short.MAX_VALUE)
                            .addComponent(sizeCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(removeBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(colourTF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(brandTF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(quantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(refreshBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(375, 375, 375))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(backBTN)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(supplierTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(brandTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(quantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(typeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(colourTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sizeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBTN)
                    .addComponent(removeBTN)
                    .addComponent(clearBTN)
                    .addComponent(editBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(refreshBTN)))
                .addGap(106, 106, 106))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        String supplier=supplierTF.getText();
        String type=typeCB.getSelectedItem().toString();
        String size=sizeCB.getSelectedItem().toString();
        String brand=brandTF.getText();
        String colour=colourTF.getText();
        String price=priceTF.getText();
        String quantity=quantityTF.getText();
        
        if(supplierTF.getText().isEmpty()||brandTF.getText().isEmpty()||colourTF.getText().isEmpty()||priceTF.getText().isEmpty()||quantityTF.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Some Information is Missing");
        }
        else{
            try{
                con = java.sql.DriverManager.getConnection(dbURL, "", "");
                PreparedStatement add = con.prepareStatement("INSERT INTO Clothes (SupplierID,Type,Colour,Brand,Size,Price,AvailableAmount) VALUES(?,?,?,?,?,?,?)");  //creating a prepared statement for ps
                add.setString(1, supplier);
                add.setString(2, type);
                add.setString(3, colour);
                add.setString(4, brand);
                add.setString(5, size);
                add.setString(6, price);
                add.setString(7, quantity);
                
                if(add.executeUpdate() > 0){
                
                JOptionPane.showMessageDialog(null, "Product Added Successfully");
            }else{
                JOptionPane.showMessageDialog(null, "Please Check The Data You Have Entered");
            }
                
            }
            catch (SQLException sqlex) {
            System.err.println("Check your SQL " + sqlex);
            sqlex.printStackTrace();
        }
            
            
        }
        
    }//GEN-LAST:event_addBTNActionPerformed

    
    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        // TODO add your handling code here:
        
        supplierTF.setText("");
        brandTF.setText("");
        colourTF.setText("");
        priceTF.setText("");
        quantityTF.setText("");
        
    }//GEN-LAST:event_clearBTNActionPerformed

    private void removeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBTNActionPerformed
        // TODO add your handling code here:
        String clothesID = JOptionPane.showInputDialog("Please Enter the Clothing ID you want to remove");
        
        if(clothesID.isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Please enter a number into the input area");
        }
        else{
            
            try{
                con = java.sql.DriverManager.getConnection(dbURL, "", "");
                PreparedStatement add = con.prepareStatement("DELETE FROM Clothes WHERE ItemID = ?");  //creating a prepared statement for ps
                add.setInt(1, Integer.parseInt(clothesID));
                int rowsAffected = add.executeUpdate();
                
                if( rowsAffected == 1){
                
                JOptionPane.showMessageDialog(null, "Product Removed Successfully");
            }else{
                JOptionPane.showMessageDialog(null, "Please Check The Data You Have Entered");
            }
                
            }
            catch (SQLException sqlex) {
            System.err.println("Check your SQL " + sqlex);
            sqlex.printStackTrace();
        }
            
            
        }
        
        
    }//GEN-LAST:event_removeBTNActionPerformed

    private void editBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTNActionPerformed
        // TODO add your handling code here:
        
        String supplier=supplierTF.getText();
        String type=typeCB.getSelectedItem().toString();
        String size=sizeCB.getSelectedItem().toString();
        String brand=brandTF.getText();
        String colour=colourTF.getText();
        String price=priceTF.getText();
        String quantity=quantityTF.getText();
        
        if(supplierTF.getText().isEmpty()||brandTF.getText().isEmpty()||colourTF.getText().isEmpty()||priceTF.getText().isEmpty()||quantityTF.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Some Information is Missing");
        }
        else{String clothesID = JOptionPane.showInputDialog("Please Enter the Clothing ID you want to Edit");
        
        if(clothesID.isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Please enter a number into the input area");
        }
        else{
            try{
                con = java.sql.DriverManager.getConnection(dbURL, "", "");
                PreparedStatement add = con.prepareStatement("UPDATE Clothes SET SupplierID = ?,Type = ?,Colour = ?,Brand = ?,Size = ?,Price = ?,AvailableAmount = ? WHERE ItemID = ?");  //creating a prepared statement for ps
                add.setString(1, supplier);
                add.setString(2, type);
                add.setString(3, colour);
                add.setString(4, brand);
                add.setString(5, size);
                add.setString(6, price);
                add.setString(7, quantity);
                add.setInt(8, Integer.parseInt(clothesID));
                
                if(add.executeUpdate() > 0){
                
                JOptionPane.showMessageDialog(null, "Product Edited Successfully");
            }else{
                JOptionPane.showMessageDialog(null, "Please Check The Data You Have Entered");
            }
                
            }
            catch (SQLException sqlex) {
            System.err.println("Check your SQL " + sqlex);
            sqlex.printStackTrace();
        }
            
        }
            
            
            
        }
    }//GEN-LAST:event_editBTNActionPerformed

    private void refreshBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBTNActionPerformed
        // TODO add your handling code here:
        getTable();
    }//GEN-LAST:event_refreshBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        dispose();
        EmployeeHome eh = new EmployeeHome();
        eh.setVisible(true);
    }//GEN-LAST:event_backBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockManagement().setVisible(true);
            }
        });
    }
    
    public void getTable() {
        model.setRowCount(0);
                        

        try {
        con = java.sql.DriverManager.getConnection(dbURL, "", "");

            PreparedStatement showTable = con.prepareStatement("SELECT * FROM Clothes");
            ResultSet rs = showTable.executeQuery();
            while (rs.next()) {
                int clothesID = rs.getInt("ItemID");
                String brand = rs.getString("Brand");
                String type = rs.getString("Type");
                String colour = rs.getString("Colour");
                String size = rs.getString("Size");
                String price = rs.getString("Price");
                String quantity = rs.getString("AvailableAmount");

                model.addRow(new Object[]{clothesID, brand, type, colour, size , price, quantity});
            }
            stockTBL.setModel(model);
            rs.close();
            showTable.close();
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JButton backBTN;
    private javax.swing.JTextField brandTF;
    private javax.swing.JButton clearBTN;
    private javax.swing.JTextField colourTF;
    private javax.swing.JButton editBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField priceTF;
    private javax.swing.JTextField quantityTF;
    private javax.swing.JButton refreshBTN;
    private javax.swing.JButton removeBTN;
    private javax.swing.JComboBox<String> sizeCB;
    private javax.swing.JTable stockTBL;
    private javax.swing.JTextField supplierTF;
    private javax.swing.JComboBox<String> typeCB;
    // End of variables declaration//GEN-END:variables
}
